// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseTable: typeof import('./src/components/common/table/BaseTable.vue')['default']
    BigFileUpload: typeof import('./src/components/common/upload/big-file-upload.vue')['default']
    Breadcrumb: typeof import('./src/components/layout/components/Breadcrumb.vue')['default']
    DarkSwitch: typeof import('./src/components/common/dark-switch/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ExportExcel: typeof import('./src/components/common/download/ExportExcel.vue')['default']
    Footer: typeof import('./src/components/layout/components/Footer.vue')['default']
    Header: typeof import('./src/components/layout/components/Header.vue')['default']
    IEpCirclePlus: typeof import('~icons/ep/circle-plus')['default']
    IEpDelete: typeof import('~icons/ep/delete')['default']
    IEpUploadFilled: typeof import('~icons/ep/upload-filled')['default']
    IEpVideoPause: typeof import('~icons/ep/video-pause')['default']
    KeywordSearch: typeof import('./src/components/common/search/KeywordSearch.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    RichTextEditor: typeof import('./src/components/common/rich-text-editor/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sider: typeof import('./src/components/layout/components/Sider.vue')['default']
    UploadTable: typeof import('./src/components/common/upload/upload-table.vue')['default']
    UseBaseTable: typeof import('./src/components/common/example/useBaseTable.vue')['default']
    UseDarkSwitch: typeof import('./src/components/common/example/useDarkSwitch.vue')['default']
    UseExportExcel: typeof import('./src/components/common/example/useExportExcel.vue')['default']
    UseRichTextEditor: typeof import('./src/components/common/example/useRichTextEditor.vue')['default']
  }
}

export {}
