// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseTable: typeof import('./src/components/common/table/BaseTable.vue')['default']
    Download: typeof import('./src/components/common/download/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    Example: typeof import('./src/components/common/rich-text-editor/example.vue')['default']
    ExportExcel: typeof import('./src/components/common/download/ExportExcel.vue')['default']
    KeywordSearch: typeof import('./src/components/common/search/KeywordSearch.vue')['default']
    RichTextEditor: typeof import('./src/components/common/rich-text-editor/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UseExample: typeof import('./src/components/common/table/useExample.vue')['default']
  }
}

export {}
