// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseTable: typeof import('./src/components/common/table/BaseTable.vue')['default']
    DarkSwitch: typeof import('./src/components/common/dark-switch/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ExportExcel: typeof import('./src/components/common/download/ExportExcel.vue')['default']
    KeywordSearch: typeof import('./src/components/common/search/KeywordSearch.vue')['default']
    OlMap: typeof import('./src/components/business/ol-map/index.vue')['default']
    RichTextEditor: typeof import('./src/components/common/rich-text-editor/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UseBaseTable: typeof import('./src/components/common/example/useBaseTable.vue')['default']
    UseDarkSwitch: typeof import('./src/components/common/example/useDarkSwitch.vue')['default']
    UseExportExcel: typeof import('./src/components/common/example/useExportExcel.vue')['default']
    UseRichTextEditor: typeof import('./src/components/common/example/useRichTextEditor.vue')['default']
  }
}

export {}
