// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CommonDarkSwitch: typeof import('./../src/components/common/dark-switch/index.vue')['default']
    CommonDownloadExportExcel: typeof import('./../src/components/common/download/ExportExcel.vue')['default']
    CommonExampleUseBaseTable: typeof import('./../src/components/common/example/useBaseTable.vue')['default']
    CommonExampleUseDarkSwitch: typeof import('./../src/components/common/example/useDarkSwitch.vue')['default']
    CommonExampleUseExportExcel: typeof import('./../src/components/common/example/useExportExcel.vue')['default']
    CommonExampleUseRichTextEditor: typeof import('./../src/components/common/example/useRichTextEditor.vue')['default']
    CommonFormBaseForm: typeof import('./../src/components/common/form/BaseForm.vue')['default']
    CommonRichTextEditor: typeof import('./../src/components/common/rich-text-editor/index.vue')['default']
    CommonSearchKeywordSearch: typeof import('./../src/components/common/search/KeywordSearch.vue')['default']
    CommonTableBaseTable: typeof import('./../src/components/common/table/BaseTable.vue')['default']
    CommonTableBaseTableColumn: typeof import('./../src/components/common/table/BaseTableColumn.vue')['default']
    CommonUploadBigFileUpload: typeof import('./../src/components/common/upload/big-file-upload.vue')['default']
    CommonUploadUploadTable: typeof import('./../src/components/common/upload/upload-table.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Exception404: typeof import('./../src/view/exception/404.vue')['default']
    Home: typeof import('./../src/view/home/index.vue')['default']
    Layout: typeof import('./../src/components/layout/index.vue')['default']
    LayoutComponentsBreadcrumb: typeof import('./../src/components/layout/components/Breadcrumb.vue')['default']
    LayoutComponentsFooter: typeof import('./../src/components/layout/components/Footer.vue')['default']
    LayoutComponentsHeader: typeof import('./../src/components/layout/components/Header.vue')['default']
    LayoutComponentsMenu: typeof import('./../src/components/layout/components/Menu.vue')['default']
    LayoutComponentsMenuItem: typeof import('./../src/components/layout/components/MenuItem.vue')['default']
    LayoutComponentsSider: typeof import('./../src/components/layout/components/Sider.vue')['default']
    Login: typeof import('./../src/view/login/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StudyThree: typeof import('./../src/view/studyThree/index.vue')['default']
  }
}

export {}
