// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CommonDarkSwitch: typeof import('./../src/components/common/dark-switch/index.vue')['default']
    CommonDownloadExportExcel: typeof import('./../src/components/common/download/ExportExcel.vue')['default']
    CommonExampleUseBaseTable: typeof import('./../src/components/common/example/useBaseTable.vue')['default']
    CommonExampleUseDarkSwitch: typeof import('./../src/components/common/example/useDarkSwitch.vue')['default']
    CommonExampleUseExportExcel: typeof import('./../src/components/common/example/useExportExcel.vue')['default']
    CommonExampleUseRichTextEditor: typeof import('./../src/components/common/example/useRichTextEditor.vue')['default']
    CommonRichTextEditor: typeof import('./../src/components/common/rich-text-editor/index.vue')['default']
    CommonSearchKeywordSearch: typeof import('./../src/components/common/search/KeywordSearch.vue')['default']
    CommonTableBaseTable: typeof import('./../src/components/common/table/BaseTable.vue')['default']
    CommonUploadBigFileUpload: typeof import('./../src/components/common/upload/big-file-upload.vue')['default']
    CommonUploadUploadTable: typeof import('./../src/components/common/upload/upload-table.vue')['default']
    Layout: typeof import('./../src/components/layout/index.vue')['default']
    LayoutComponentsBreadcrumb: typeof import('./../src/components/layout/components/Breadcrumb.vue')['default']
    LayoutComponentsFooter: typeof import('./../src/components/layout/components/Footer.vue')['default']
    LayoutComponentsHeader: typeof import('./../src/components/layout/components/Header.vue')['default']
    LayoutComponentsMenu: typeof import('./../src/components/layout/components/Menu.vue')['default']
    LayoutComponentsMenuItem: typeof import('./../src/components/layout/components/MenuItem.vue')['default']
    LayoutComponentsSider: typeof import('./../src/components/layout/components/Sider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
